### ISSUE TITLE
Sometimes, match result is greater than 100% (not a normal behavior!)

### ISSUE THREAD

**Issue by bebenlebricolo** [bebenlebricolo/FreeMyCode#13]

**Comment by FoxP** [comment]
Greater than 100% ? That's a feature, do not underestimate yourself !

**Comment by bebenlebricolo** [comment]
Now closed, this has been fixed in commit [d77c70f5f6b01d314141675a3e258a040a0658d8](https://github.com/bebenlebricolo/FreeMyCode/commit/d77c70f5f6b01d314141675a3e258a040a0658d8).

Comments in files were not parsed as good as I expected, this behavior has been fixed.
In the same time, wrong comment parsing resulted in wrong match patterns, and percentage calculation had to be revised in the same time.
